// <auto-generated />
using System;
using GamblingBuddies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamblingBuddies.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526231911_AddPayUFieldsToPayment")]
    partial class AddPayUFieldsToPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamblingBuddies.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GamblingBuddies.Models.DocumentFile", b =>
                {
                    b.Property<int>("DocumentFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentFileId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentFileId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentFiles");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("EmployeePositionDictionaryId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeStatusDictionaryId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeStatusDictionaryId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GamblingBuddies.Models.EmployeeAssignment", b =>
                {
                    b.Property<int>("EmployeeAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAssignmentId"));

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeAssignmentId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("EmployeeAssignments");
                });

            modelBuilder.Entity("GamblingBuddies.Models.EmployeePositionDictionary", b =>
                {
                    b.Property<int>("EmployeePositionDictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeePositionDictionaryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeePositionDictionaryId");

                    b.ToTable("EmployeePositionDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.EmployeeStatusDictionary", b =>
                {
                    b.Property<int>("EmployeeStatusDictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeStatusDictionaryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeStatusDictionaryId");

                    b.ToTable("EmployeeStatusDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("GameCategoryId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameCategoryDictionary", b =>
                {
                    b.Property<int>("GameCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameCategoryId");

                    b.ToTable("GameCategoryDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameSession", b =>
                {
                    b.Property<int>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameSessionId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameTableId")
                        .HasColumnType("int");

                    b.Property<int>("GameVariantId")
                        .HasColumnType("int");

                    b.Property<int>("SessionStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GameSessionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GameTableId");

                    b.HasIndex("GameVariantId");

                    b.HasIndex("SessionStatusId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameTable", b =>
                {
                    b.Property<int>("GameTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameTableId"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("GameTableId");

                    b.HasIndex("HallId");

                    b.ToTable("GameTables");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameVariant", b =>
                {
                    b.Property<int>("GameVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameVariantId"));

                    b.Property<decimal>("DefaultMaxBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultMinBet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameVariantId");

                    b.HasIndex("GameId");

                    b.ToTable("GameVariants");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Hall", b =>
                {
                    b.Property<int>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HallTypeDictionaryHallTypeId")
                        .HasColumnType("int");

                    b.Property<int>("HallTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HallId");

                    b.HasIndex("HallTypeDictionaryHallTypeId");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("GamblingBuddies.Models.HallTypeDictionary", b =>
                {
                    b.Property<int>("HallTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HallTypeId");

                    b.ToTable("HallTypeDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentProviderOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GamblingBuddies.Models.PaymentMethodDictionary", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("GamblingBuddies.Models.PaymentReport", b =>
                {
                    b.Property<int>("PaymentReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentReportId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiltersApplied")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("int");

                    b.HasKey("PaymentReportId");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("PaymentReports");
                });

            modelBuilder.Entity("GamblingBuddies.Models.PaymentStatusDictionary", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentStatusId");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("GamblingBuddies.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderResponseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReportDefinition", b =>
                {
                    b.Property<int>("ReportDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportDefinitionId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryTemplate_or_Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportDefinitionId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ReportDefinitions");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReportExecution", b =>
                {
                    b.Property<int>("ReportExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportExecutionId"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("ReportExecutionId");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex("ReportDefinitionId");

                    b.ToTable("ReportExecutions");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReservationStatusId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReservationSeat", b =>
                {
                    b.Property<int>("ReservationSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationSeatId"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("ReservationSeatId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.ToTable("ReservationSeats");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReservationStatusDictionary", b =>
                {
                    b.Property<int>("ReservationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationStatusId");

                    b.ToTable("ReservationStatusDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GamblingBuddies.Models.RoleDictionary", b =>
                {
                    b.Property<int>("RoleDictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleDictionaryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleDictionaryId");

                    b.ToTable("RoleDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("TableId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("GamblingBuddies.Models.SessionStatusDictionary", b =>
                {
                    b.Property<int>("SessionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionStatusId");

                    b.ToTable("SessionStatusDictionaries");
                });

            modelBuilder.Entity("GamblingBuddies.Models.SystemUser", b =>
                {
                    b.Property<int>("SystemUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemUserId");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("GamblingBuddies.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleDictionaryId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleDictionaryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("GamblingBuddies.Models.WorkShift", b =>
                {
                    b.Property<int>("WorkShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkShiftId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkShiftId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("GamblingBuddies.Models.AuditLog", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Document", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Payment", null)
                        .WithMany("Documents")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GamblingBuddies.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("GamblingBuddies.Models.DocumentFile", b =>
                {
                    b.HasOne("GamblingBuddies.Models.Document", "Document")
                        .WithMany("DocumentFile")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Employee", b =>
                {
                    b.HasOne("GamblingBuddies.Models.EmployeeStatusDictionary", "Status")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusDictionaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.EmployeePositionDictionary", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Position");

                    b.Navigation("Status");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("GamblingBuddies.Models.EmployeeAssignment", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Employee");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Game", b =>
                {
                    b.HasOne("GamblingBuddies.Models.GameCategoryDictionary", "GameCategory")
                        .WithMany("Games")
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameCategory");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameSession", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.GameTable", "GameTable")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.GameVariant", "GameVariant")
                        .WithMany()
                        .HasForeignKey("GameVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.SessionStatusDictionary", "SessionStatus")
                        .WithMany("GameSessions")
                        .HasForeignKey("SessionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("GameTable");

                    b.Navigation("GameVariant");

                    b.Navigation("SessionStatus");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameTable", b =>
                {
                    b.HasOne("GamblingBuddies.Models.Hall", "Hall")
                        .WithMany("GameTables")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameVariant", b =>
                {
                    b.HasOne("GamblingBuddies.Models.Game", "Game")
                        .WithMany("GameVariants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Hall", b =>
                {
                    b.HasOne("GamblingBuddies.Models.HallTypeDictionary", null)
                        .WithMany("Halls")
                        .HasForeignKey("HallTypeDictionaryHallTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GamblingBuddies.Models.Payment", b =>
                {
                    b.HasOne("GamblingBuddies.Models.PaymentMethodDictionary", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.PaymentStatusDictionary", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("GamblingBuddies.Models.PaymentReport", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("GamblingBuddies.Models.PaymentTransaction", b =>
                {
                    b.HasOne("GamblingBuddies.Models.Payment", "Payment")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReportDefinition", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReportExecution", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.ReportDefinition", "ReportDefinition")
                        .WithMany()
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");

                    b.Navigation("ReportDefinition");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Reservation", b =>
                {
                    b.HasOne("GamblingBuddies.Models.GameSession", "GameSession")
                        .WithMany("Reservations")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.ReservationStatusDictionary", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");

                    b.Navigation("ReservationStatus");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReservationSeat", b =>
                {
                    b.HasOne("GamblingBuddies.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Reservation", "Reservation")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Seat", "Seat")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Reservation");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Seat", b =>
                {
                    b.HasOne("GamblingBuddies.Models.GameTable", "Table")
                        .WithMany("Seats")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("GamblingBuddies.Models.UserRole", b =>
                {
                    b.HasOne("GamblingBuddies.Models.RoleDictionary", "RoleDictionary")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleDictionaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GamblingBuddies.Models.SystemUser", "SystemUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleDictionary");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("GamblingBuddies.Models.WorkShift", b =>
                {
                    b.HasOne("GamblingBuddies.Models.SystemUser", "CreatedByUser")
                        .WithMany("WorkShiftsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamblingBuddies.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Document", b =>
                {
                    b.Navigation("DocumentFile");
                });

            modelBuilder.Entity("GamblingBuddies.Models.EmployeePositionDictionary", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GamblingBuddies.Models.EmployeeStatusDictionary", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Game", b =>
                {
                    b.Navigation("GameVariants");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameCategoryDictionary", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameSession", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("GamblingBuddies.Models.GameTable", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Hall", b =>
                {
                    b.Navigation("GameTables");
                });

            modelBuilder.Entity("GamblingBuddies.Models.HallTypeDictionary", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Payment", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationSeats");
                });

            modelBuilder.Entity("GamblingBuddies.Models.ReservationStatusDictionary", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GamblingBuddies.Models.RoleDictionary", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GamblingBuddies.Models.Seat", b =>
                {
                    b.Navigation("ReservationSeats");
                });

            modelBuilder.Entity("GamblingBuddies.Models.SessionStatusDictionary", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("GamblingBuddies.Models.SystemUser", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("WorkShiftsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
